name: Build Mesa Turnip

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: "Branch"
        required: true
        default: 'main'
      A750_FIX:
        description: "A750 Fix"
        required: true
        default: false
        type: boolean
      MAGISK:
        description: "Magisk Module"
        required: true
        default: false
        type: boolean
      ADRENOTOOL:
        description: "Adreno Tool"
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prepare Environment
      run: |
        sudo apt remove meson firefox -y
        sudo pip3 install --upgrade meson ninja mako

    - name: Execute Build Script
      run: bash ./turnip_builder.sh $GITHUB_ENV ${{ github.event.inputs.BRANCH }} ${{ github.event.inputs.A750_FIX }} ${{ github.event.inputs.MAGISK }} ${{ github.event.inputs.ADRENOTOOL }}

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TurnipDriver_${{ env.MESA_VERSION }}_${{ env.VULKAN_VERSION }}_${{ env.DATA }}
        compression-level: 9
        path: turnip_workdir/*