name: Build Mesa Turnip

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prepare Environment
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo apt remove firefox -y
        sudo apt update
        sudo apt upgrade
        sudo apt build-dep mesa -y
        sudo pip3 install --upgrade meson

    - name: Execute Build Script
      run: bash ./turnip_builder.sh

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Upload Snapshot
        compression-level: 9
        path: turnip_workdir/mesa-main/build-android-aarch64/src/freedreno/vulkan/libvulkan_freedreno.so